---
- hosts: dsl_www
  vars: # see https://github.com/geerlingguy/ansible-role-apache for apache-specific vars definitions
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_remove_default_vhost: true
    apache_mods_enabled:
      - proxy.load
      - proxy_http.load
      - ssl.load
    apache_global_settings: |
      DirectoryIndex index.php

    apache_vhosts:
      - servername: "{{ domain }}"
        documentroot: "{{ apache_doc_root }}"

  roles:
    - common
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
  become: true
